# Generated by Django 3.0 on 2020-11-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfSick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='diagnosise',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosise',
            name='prescription_id',
        ),
        migrations.AddField(
            model_name='diagnosise',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Prescription'),
        ),
        migrations.AddField(
            model_name='diagnosise',
            name='sick',
            field=models.ManyToManyField(related_name='diagnosise_sick', to='doctor.Sick'),
        ),
    ]
