# Generated by Django 3.0 on 2020-11-16 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20201116_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosise',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='diagnosise',
            name='pregnant',
        ),
        migrations.RemoveField(
            model_name='diagnosise',
            name='x_ray',
        ),
        migrations.AddField(
            model_name='diagnosise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
