# Generated by Django 3.0 on 2020-11-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_title'),
        ('doctor', '0002_delete_diagnosise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='nurseId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='nurseId',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
