# Generated by Django 3.0 on 2020-11-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20201118_1202'),
        ('doctor', '0003_auto_20201118_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='prescription',
        ),
        migrations.CreateModel(
            name='PrescriptionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('drugId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.StoreDrug')),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Payment')),
            ],
        ),
    ]
