# Generated by Django 3.0 on 2020-11-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionDetail',
        ),
    ]
