# Generated by Django 3.0 on 2020-11-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20201118_1555'),
        ('patient', '0002_delete_prescriptiondetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
