# Generated by Django 3.0 on 2020-11-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201112_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
    ]
