# Generated by Django 3.0 on 2020-11-20 10:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_description', models.CharField(blank=True, max_length=255)),
                ('rule_parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('active_screening', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
