version: "3.0"
services:
  db:
    image: postgres:11.9-alpine
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qeKmEKR52
    ports:
      - 5432:5432
    networks:
      - djangonetwork
  web-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    command: >
      sh -c "pipenv run python manage.py makemigrations; \
            pipenv run python manage.py migrate; \
            pipenv run python manage.py loaddata permissions; \
            echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" | pipenv run python3 manage.py shell; \
            pipenv run python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DATABASE_URL: postgres://admin:qeKmEKR52@db:5432/clinic
    depends_on:
      - db
    links:
      - db:db
    restart: always
    networks:
      - djangonetwork
networks:
    djangonetwork:
      driver: bridge
