version: "3.0"
services:
  db:
    image: postgres:11.9-alpine
    networks:
      - webnet
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qeKmEKR52
    ports:
      - 5433:5432
  web:
    image: "clinic:latest"
    volumes:
      - "./:/app"
    networks:
      - webnet
    ports:
      - 8000:8000
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://admin:qeKmEKR52@db:5432/clinic
    depends_on:
      - db
networks:
  webnet: null
