build:
	docker-compose -f docker-compose.dev.yml -p clinic --build
up:
	docker-compose -f docker-compose.dev.yml -p clinic up -d
reset:
	docker-compose -f docker-compose.dev.yml -p clinic down
	docker-compose -f docker-compose.dev.yml -p clinic up -d
